### ISSUE TITLE
Support predicates / operators in query

### ISSUE THREAD

**Issue by yihozhang** [mwillsey/egg-smol#11]
For many applications, we may want to write something like
```
(rule ((> (lo x) (hi x))) ((unsound x))
```
and
```
(rule ((= (typeof (Cons y ty ctx) x) t) (!= x y))((= (typeof ctx x) (typeof ctx x))))
```
However, we need to support predicates (and operators in general) for queries (the left-hand side) for this rule to work. And to support them, we may need to build a dependency graph for the query to the evaluation order (e.g., we need to ground `x` and `y` before evaluating `(!= x y)`.

**Comment by mwillsey** [comment]
This is done!
