### ISSUE TITLE
Matching bug with `!=`

### ISSUE THREAD

**Issue by oflatt** [mwillsey/egg-smol#118]
[This program](https://www.mwillsey.com/egg-smol/?program=XQAAgAD9AQAAAAAAAAAUGQgnfMUD9dO1z8bgG1j6Z2ICO_M_I1psYVAa2WxYU__A95d1Q5gciSWq1xBjbIPntopOXZf_4G6VhK6XnWh7XcqmuMa7802madAYlTjmCp61NQ9q2PDhBdEt30wmetQjjdQz0ql515ouZ-nYsfIwbHjwfQbB0p5W4ODHM-Fc-whFs3zwKKUE55eSFHJXnzZ68Wxzag_8oceoTA23FLqxt7L-vSi2mqk4a2P424f1AcKMzCXx-EqXa2VrzF2_a-pSmzsKctWit5hrp9za1N66CLEqnP_tWTXOAoA62GVm8U8uWwJZgl8OOI_lPuNC5bQoDf777io%253D) should be the same if you use the commented out rule. However, it fails.

**Comment by mwillsey** [comment]
Is this the right example? Where is the != ?

**Comment by ezrosent** [comment]
If I run this for `30` it passes. Are we sure it's a bug, and not just rules taking longer to match?

**Comment by oflatt** [comment]
Oh you are right, it just takes more iterations because it needs to fire the fire rule separately. Thanks!
