### ISSUE TITLE
lattices should be bounded (rationals -> extended rationals)

### ISSUE THREAD

**Issue by yihozhang** [mwillsey/egg-smol#12]
The semantics of rewrite rules is that everything on the LHS is query, and everything on the RHS is action (populating terms only, no query). For example, in
```
(rewrite ((add a b)) ((= (lo x) (+ (lo a) (lo b)))))
```
`(lo x)`, `(lo a)`, `(lo b)` will be created on the fly with the default bottom value (so the above is usually not the rule we want). For this to be true, lattices should have a least element.

**Comment by yihozhang** [comment]
Looking back at my egg# tutorial, I think the semantics we wanted is "analysis relations has a default, but the default is not necessarily the lattice bottom", so we can support normal functions like (in egg# syntax):
```
rel add1(i: i64) -> i64(i + 1).
```

In egg#, lattices are implicitly bounded (bottom is "does not exist" and top is crash), so if this is true for egg-smol, implementations of lattices do not need to be bounded. However, to support default values for rationals, we still need to extend rationals with oo and -oo as default values for relations like lo and hi.

**Comment by mwillsey** [comment]
I think we can close this based on in-person conversations. Essentially, it's not the engines problem at the moment, this should be checked at a higher level.
