### ISSUE TITLE
Lambda Calculus Example in Paper

### ISSUE THREAD

**Issue by saulshanabrook** [mwillsey/egg-smol#137]
I am trying to create a lambda calculus example in the Python bindings and was curious about the code that is listed in the ["Better Together: Unifying Datalog and Equality Saturation" paper](https://arxiv.org/abs/2304.04332v2):

<img width="401" alt="Screenshot 2023-04-26 at 8 36 56 PM" src="https://user-images.githubusercontent.com/1186124/234730832-af9cb388-1966-499f-8579-d66f39dc4e59.png">

It looks a bit different than [the current lambda calculus example in this repo](https://github.com/mwillsey/egg-smol/blob/30feaaab88452ec4b6c5f7a199345298bac2dd0f/tests/lambda.egg). I was curious if the code for the paper is living somewhere else and if it works on the most recent version of egg-smol.

**Comment by yihozhang** [comment]
oh yeah the code in the paper is mostly for illustration purposes and does not work directly in egg-smol. It simplifies some details and uses a slightly different syntax (e.g., we have `define` instead of `let`).

**Comment by saulshanabrook** [comment]
@yihozhang Sounds good! I'll just rely on the example in the repo then, thank you.

**Comment by mwillsey** [comment]
Also it reflects the state of egg-smol at submission time.
