### ISSUE TITLE
Merge during rebuild

### ISSUE THREAD

**Issue by ezrosent** [mwillsey/egg-smol#42]
Today merge functions are only applied when we notice a merge while evaluating `Action::Set`, but we can also cause merges during a `rebuild`. Merge functions should also run in response to merges caused by rebuilds. Here's a small failing test case:
```
(datatype N (Node i64))
(function distance (N N) i64 :merge (min old new))

(define a (Node 0))
(define b (Node 1))
(define x (Node 2))
(define y (Node 3))
(set (distance x y) 1)
(set (distance a b) 2)

(union a x)
(union b y)

(run 1)
(check (= (distance x y) 1)) ; fails, the distance has gone up!
```

**Comment by yihozhang** [comment]
@mwillsey @ezrosent what's the latest status on this issue? I'm actually surprised that this has not caused any real problems so far.

**Comment by mwillsey** [comment]
This seems to still fail. Me too, I am surprised. I won't have time to fix for a while though :(

**Comment by ezrosent** [comment]
I can take a stab at this this week.

**Comment by ezrosent** [comment]
Sent a PR with a fix (this took less time than I thought!)
