### ISSUE TITLE
Define command vs define action

### ISSUE THREAD

**Issue by saulshanabrook** [mwillsey/egg-smol#67]
There is currently both a top-level define command as well as a define action, with the same names and similar signatures, but different behavior. This was initially a bit confusing for me until I dug into the source and tried out some examples. I am opening this issue to document my understanding of the current behavior (please correct me where I am wrong) and open a discussion to see if there might be a way to make it more straightforward. 

### Top level define command

The top level command is effectively an alias for defining a function that takes no args (a thunk) and setting the value passed in as the result. So for example, I can do:

```lisp
(define x 1)
(check (= (x) 1))
```

Which is, AFAIK, equivalent to:

```lisp
(function x () i64)
(set (x) 1)
(check (= (x) 1))
```

The `define` top-level command is used in many examples to make variables which are then referred to later.

### Define action

The define action however cannot currently be run at the top level of the script but can be used in a rule, to define a temporary local variable that is then accessed later in the rule actions.

For example, this is the initial `fibonacci` example:

```lisp
(function fib (i64) i64)
(set (fib 0) 0)
(set (fib 1) 1)

(rule ((= f0 (fib x))
       (= f1 (fib (+ x 1))))
      ((set (fib (+ x 2)) (+ f0 f1))))

(run 7)

(check (= (fib 7) 13))
```

We can refactor it to define a temporary variable in the rule and use that to set the value:

```lisp
(function fib (i64) i64)
(set (fib 0) 0)
(set (fib 1) 1)

(rule ((= f0 (fib x))
       (= f1 (fib (+ x 1))))
      ((define sum (+ f0 f1))
       (set (fib (+ x 2)) sum)))

(run 7)

(check (= (fib 7) 13))
```

This is different from the above define, in that it sets it as a variable, not as a function. So you cannot call the `sum` in the `set` action below it.

As far as I can tell, this isn't used much at all in the examples. The only place I can see it used is in the `matrix` example. In this case, the local variables defined are not ever actually accessed later. I assume something about simply defining them has an affect on the script, but I am not sure what this is:

```
; demand
(rule ((= e (MMul A B)))
((define demand1 (ncols A))
(define demand2 (nrows A))
(define demand3 (ncols B))
(define demand4 (nrows B)))
)
```

## Possible changes

As I said above, I am not opening this because there are any bugs in the current implementation necessary, but simply because the ergonomic are a bit confusing. Depending on where the define is located it can either be a global function or a local variable. Also the top level one takes a cost parameter, which the local variable does not. 

I wonder if it might be possible to either:

1. Remove the define action since it is used in only one example. In that case, it isn’t used for defining a variable but for causing a value to be evaluated. Maybe if this use case is still needed, there could be a different action defined to only evaluate the expression?
2. Change the name of one of them, to differentiate them better.
3. Keep them the same, but maybe make their implementation closer? Maybe the top-level one could also set a global variable, instead of defining a function?
4. Remove the define command, since you can get the same behavior with a function definition and a set, or just repeat the expression where you need. This would be fine for using egg-smol from something like Python, where you can rely on the host language to define a value and use it in multiple places, but would make the text interface much more verbose.

These are just a few initial ideas I had, but I mostly wanted to raise this issue to make sure I am understanding things properly and open up the discussion for more input. Thank you all for your work on this package! It's been very interesting to dive into and learn about.

**Comment by mwillsey** [comment]
This is a great point and totally correct. My initial take is that we
should rename them to be separate. Perhaps “let” for the action?
