### ISSUE TITLE
Persistent indices across updates

### ISSUE THREAD

**Issue by yihozhang** [mwillsey/egg-smol#7]
Rebuilding Indices is one of the performance bottleneck of relational e-matching. Right now, the indices are built from scratch in each iteration. A more efficient approach may be to keep the indices across iterations and keep them updated as the database changes.

**Comment by ezrosent** [comment]
By the same token, could canonicalization also be incremental? If we stored "all-eid" relations in a trie that listed each column (with the eclass id at the leaf), then the same incremental merging operation performed on indices could also be used to merge eclasses, with new collisions at the leaves triggering an additional merge.

**Comment by mwillsey** [comment]
Closing for now, as we've decided to table this.
